import { Link } from "wouter";
import { ArrowRight, Check, Clock3, MapPin, Plus, ShoppingBag, Sparkles, Utensils } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { StorefrontCartCheckout } from "@/components/StorefrontCartCheckout";
import type { Storefront } from "@/lib/useStorefront";

/** The original warm, editorial storefront look. */
export function ClassicTemplate(s: Storefront) {
  const company = s.company!;
  const brandColor = company.primaryColor || "#a05c32";

  return <div className="min-h-screen bg-[#fbfaf7] text-[#29251f]">
    <header className="sticky top-0 z-30 border-b border-[#e9e3d9]/80 bg-[#fbfaf7]/90 backdrop-blur-xl">
      <div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-5 lg:px-8">
        <div className="flex items-center gap-3">
          {company.logoUrl ? <img src={company.logoUrl} alt={company.name} className="h-10 w-10 rounded-2xl object-cover" /> : <div className="brand-mark" style={{ backgroundColor: brandColor }}><Utensils className="h-5 w-5" /></div>}
          <div><p className="font-display text-xl font-bold leading-none tracking-tight">{company.name}</p><p className="mt-1 text-[10px] font-semibold uppercase tracking-[0.22em] text-[#a06b3b]">{company.tagline || "comida de verdade"}</p></div>
        </div>
        <nav className="hidden items-center gap-8 text-sm font-medium text-[#776e63] md:flex"><a href="#cardapio" className="hover:text-[#a05c32]">Cardápio</a><a href="#como-funciona" className="hover:text-[#a05c32]">Como funciona</a><a href="#historia" className="hover:text-[#a05c32]">Nossa cozinha</a></nav>
        <div className="flex items-center gap-3"><Link href={`/${s.slug}/admin`}><Button variant="ghost" className="hidden text-[#776e63] hover:bg-[#f1ece3] sm:flex">Área da cozinha</Button></Link><Button aria-label={`Abrir pedido${s.totalItems > 0 ? ` com ${s.totalItems} itens` : ""}`} onClick={() => s.setCartOpen(true)} className="relative rounded-full bg-[#2f5d50] px-4 text-white shadow-lg shadow-[#2f5d50]/15 hover:bg-[#254a40]"><ShoppingBag className="mr-2 h-4 w-4" /> Pedido {s.totalItems > 0 && <span className="ml-2 flex h-5 min-w-5 items-center justify-center rounded-full bg-[#e8bd72] px-1 text-xs font-bold text-[#382718]">{s.totalItems}</span>}</Button></div>
      </div>
    </header>

    <main>
      <section className="relative overflow-hidden"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 pb-18 pt-16 lg:grid-cols-[0.9fr_1.1fr] lg:px-8 lg:pb-24 lg:pt-22"><div className="relative z-10"><div className="eyebrow"><Sparkles className="h-3.5 w-3.5" /> Feita hoje, do nosso fogão para você</div><h1 className="mt-6 max-w-xl font-display text-5xl font-bold leading-[0.98] tracking-[-0.055em] text-[#29251f] sm:text-6xl lg:text-[78px]">Almoço com gosto de <em className="text-[#a05c32]">casa.</em></h1><p className="mt-7 max-w-md text-[17px] leading-8 text-[#776e63]">Marmitas generosas, ingredientes frescos e aquele cuidado que transforma uma refeição comum no melhor momento do dia.</p><div className="mt-9 flex flex-wrap items-center gap-4"><a href="#cardapio"><Button size="lg" className="h-13 rounded-full bg-[#a05c32] px-7 text-white shadow-lg shadow-[#a05c32]/20 hover:bg-[#8a4e2b]">Ver o cardápio <ArrowRight className="ml-2 h-4 w-4" /></Button></a><span className="text-sm text-[#776e63]">Feita em pequenos lotes, todos os dias.</span></div><div className="mt-12 flex items-center gap-7 border-t border-[#e9e3d9] pt-6 text-sm text-[#776e63]"><span className="flex items-center gap-2"><Clock3 className="h-4 w-4 text-[#a05c32]" /> 11h às 14h30</span><span className="flex items-center gap-2"><MapPin className="h-4 w-4 text-[#a05c32]" /> Entrega em até 45 min</span></div></div><div className="hero-photo-wrap"><div className="hero-photo"/><div className="hero-note"><span className="note-icon"><Check className="h-4 w-4" /></span><div><p className="font-semibold text-[#29251f]">Cardápio do dia</p><p className="text-xs text-[#776e63]">preparado com carinho</p></div></div><div className="hero-sun"/></div></div></section>

      <section id="cardapio" className="mx-auto max-w-7xl scroll-mt-24 px-5 py-16 lg:px-8"><div className="mb-9 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="section-kicker">Escolha seu momento</p><h2 className="mt-2 font-display text-4xl font-bold tracking-tight">O cardápio de hoje</h2><p className="mt-2 text-[#776e63]">Tudo feito em pequenos lotes para chegar fresco até você.</p></div><div className="flex items-center gap-2 text-sm text-[#776e63]"><span className="h-2 w-2 rounded-full bg-[#4f8b68]" /> Pedidos abertos até 14h30</div></div>{s.menuQuery.isLoading && <p role="status" className="mb-4 text-sm text-[#776e63]">Atualizando o cardápio...</p>}{s.menuQuery.isError && <p role="alert" className="mb-4 rounded-xl bg-[#fff0d7] px-4 py-3 text-sm text-[#8a4e2b]">Não foi possível atualizar o cardápio agora. Exibindo a seleção disponível.</p>}{s.visibleMenu.length === 0 && !s.menuQuery.isLoading && <p className="mb-4 rounded-xl bg-white px-4 py-5 text-sm text-[#776e63]">Nenhum item está disponível neste momento.</p>}<div className="category-scroll mb-8 flex gap-2 overflow-x-auto pb-2">{s.categories.map((category) => <button key={category} onClick={() => s.setActiveCategory(category)} className={`whitespace-nowrap rounded-full px-5 py-2.5 text-sm font-semibold transition ${s.activeCategory === category ? "bg-[#2f5d50] text-white shadow-md shadow-[#2f5d50]/15" : "bg-white text-[#776e63] ring-1 ring-[#e9e3d9] hover:bg-[#f4efe7]"}`}>{category}</button>)}</div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{s.visibleMenu.map((item) => <Card key={item.id} className="menu-card overflow-hidden border-0 bg-white shadow-[0_10px_40px_rgba(67,48,32,0.06)]"><div className="relative h-56 overflow-hidden"><img src={item.image} alt={item.name} className="h-full w-full object-cover transition duration-500 hover:scale-105"/><div className="absolute left-4 top-4"><Badge className="border-0 bg-[#fbfaf7]/90 text-[#8a4e2b] shadow-sm backdrop-blur">{item.tag}</Badge></div></div><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-display text-xl font-bold">{item.name}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-[#776e63]">{item.description}</p></div><span className="whitespace-nowrap font-display text-xl font-bold text-[#a05c32]">R$ {item.price.toFixed(2).replace(".", ",")}</span></div><Button onClick={() => s.add(item.id)} className="mt-5 h-11 w-full rounded-xl bg-[#f1ece3] font-semibold text-[#2f5d50] shadow-none hover:bg-[#e6ded1]">Adicionar ao pedido <Plus className="ml-2 h-4 w-4" /></Button></CardContent></Card>)}</div></section>

      <section id="como-funciona" className="bg-[#2f5d50] px-5 py-16 text-white lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><p className="section-kicker light">Sem complicação</p><h2 className="mt-3 max-w-md font-display text-4xl font-bold leading-tight">Do nosso fogão até a sua mesa.</h2><p className="mt-4 max-w-md leading-7 text-white/70">Você escolhe, a gente prepara na hora e entrega com o mesmo cuidado de quando serviríamos na nossa própria mesa.</p></div><div className="grid gap-4 sm:grid-cols-3">{[["01", "Escolha", "Monte sua marmita no cardápio do dia."], ["02", "Pague", "Pix ou cartão, após ativar o Mercado Pago."], ["03", "Receba", "Acompanhe seu pedido após ativar a entrega."]].map(([number, title, text]) => <div key={number} className="rounded-2xl border border-white/10 bg-white/5 p-5"><span className="font-display text-3xl font-bold text-[#e8bd72]">{number}</span><h3 className="mt-7 font-display text-xl font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-white/60">{text}</p></div>)}</div></div></div></section>
      <section id="historia" className="mx-auto max-w-7xl px-5 py-18 lg:px-8"><div className="grid gap-10 rounded-[28px] bg-[#f1ece3] p-8 sm:p-12 lg:grid-cols-[1fr_1fr] lg:items-center"><div><p className="section-kicker">Nossa cozinha</p><h2 className="mt-3 max-w-md font-display text-4xl font-bold leading-tight">Comida honesta, bonita e sem pressa.</h2><p className="mt-5 max-w-lg leading-7 text-[#776e63]">{company.name} nasceu para resgatar o almoço que tem textura, aroma e história. Ingredientes simples, técnica cuidadosa e um cardápio que muda com o que está mais bonito na feira.</p><Button variant="outline" className="mt-7 rounded-full border-[#cdbfae] bg-transparent text-[#2f5d50] hover:bg-white">Conheça nosso jeito <ArrowRight className="ml-2 h-4 w-4" /></Button></div><div className="story-photo"/></div></section>
    </main>
    <footer className="border-t border-[#e9e3d9] px-5 py-8 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 text-sm text-[#776e63] sm:flex-row"><p>© 2026 {company.name}. Feita para alimentar bem.</p><p>Seg a sex · 11h às 14h30</p></div></footer>

    <StorefrontCartCheckout {...s} />
  </div>;
}
