import { ArrowRight, Check, Minus, Plus, ShoppingBag, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Separator } from "@/components/ui/separator";
import { toast } from "sonner";
import { MercadoPagoBrick } from "@/components/MercadoPagoBrick";
import type { Storefront } from "@/lib/useStorefront";

/** Cart + checkout drawers, shared by every storefront template — only the page layout around it differs. */
export function StorefrontCartCheckout(s: Storefront) {
  return <>
    <Sheet open={s.cartOpen} onOpenChange={s.setCartOpen}><SheetContent className="w-full overflow-y-auto bg-[#fbfaf7] sm:max-w-md"><SheetHeader><SheetTitle className="font-display text-2xl">Seu pedido <span className="text-sm font-normal text-[#776e63]">({s.totalItems} itens)</span></SheetTitle></SheetHeader>{s.orderHistory.length > 0 && <div className="mt-4 rounded-xl border border-[#e9e3d9] bg-white p-3"><p className="text-xs font-semibold uppercase tracking-wide text-[#a05c32]">Seu histórico neste aparelho</p><div className="mt-2 space-y-2">{s.orderHistory.slice(0, 3).map((saved, index) => <button key={`${saved.createdAt}-${index}`} onClick={() => s.repeatSavedOrder(saved)} className="flex w-full items-center justify-between rounded-lg px-2 py-2 text-left text-sm hover:bg-[#fbfaf7]"><span>Pedido salvo · {new Date(saved.createdAt).toLocaleDateString("pt-BR")}</span><span className="text-[#2f5d50]">Repetir</span></button>)}</div></div>}<div className="mt-7 space-y-5">{s.cartDetails.length === 0 ? <div className="rounded-2xl bg-white p-8 text-center"><ShoppingBag className="mx-auto h-8 w-8 text-[#cdbfae]"/><p className="mt-3 font-semibold">Seu pedido está vazio</p><p className="mt-1 text-sm text-[#776e63]">Escolha uma delícia do cardápio para começar.</p></div> : <>{s.cartDetails.map(({ item, qty, observation }) => <div key={item.id} className="rounded-2xl bg-white p-4 shadow-sm"><div className="flex gap-3"><img src={item.image} className="h-16 w-16 rounded-xl object-cover"/><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><p className="font-semibold">{item.name}</p><button onClick={() => s.changeQty(item.id, -qty)} aria-label="Remover item"><X className="h-4 w-4 text-[#a79b8d]"/></button></div><p className="mt-1 text-sm text-[#a05c32]">R$ {(item.price * qty).toFixed(2).replace(".", ",")}</p><div className="mt-3 flex items-center justify-between"><div className="flex items-center gap-2 rounded-full bg-[#f1ece3] p-1"><button onClick={() => s.changeQty(item.id, -1)} className="rounded-full p-1 hover:bg-white"><Minus className="h-3 w-3"/></button><span className="w-4 text-center text-sm font-semibold">{qty}</span><button onClick={() => s.add(item.id)} className="rounded-full p-1 hover:bg-white"><Plus className="h-3 w-3"/></button></div><span className="text-xs text-[#776e63]">Observação abaixo</span></div></div></div><Textarea value={observation} onChange={(e) => s.updateObservation(item.id, e.target.value)} placeholder="Ex.: sem cebola, molho à parte..." className="mt-3 min-h-16 resize-none border-[#e9e3d9] bg-[#fbfaf7] text-xs"/></div>)}</>}
      {s.cartDetails.length > 0 && <><Separator/><div className="space-y-3 text-sm"><div className="flex justify-between text-[#776e63]"><span>Subtotal</span><span>R$ {s.subtotal.toFixed(2).replace(".", ",")}</span></div><div className="flex justify-between text-[#776e63]"><span>Entrega</span><span>R$ {s.delivery.toFixed(2).replace(".", ",")}</span></div><div className="flex justify-between text-lg font-bold"><span>Total</span><span className="text-[#a05c32]">R$ {s.total.toFixed(2).replace(".", ",")}</span></div></div><Button onClick={() => s.setCheckoutOpen(true)} className="h-12 w-full rounded-xl bg-[#a05c32] text-white hover:bg-[#8a4e2b]">Continuar para pagamento <ArrowRight className="ml-2 h-4 w-4"/></Button></>}
    </div></SheetContent></Sheet>

    <Sheet open={s.checkoutOpen} onOpenChange={s.setCheckoutOpen}><SheetContent className="w-full overflow-y-auto bg-[#fbfaf7] sm:max-w-md"><SheetHeader><SheetTitle className="font-display text-2xl">Quase na mesa</SheetTitle></SheetHeader><div className="mt-4 rounded-2xl bg-[#f1ece3] p-4 text-sm text-[#776e63]">Você não precisa criar uma conta. Salvaremos seus dados apenas para acompanhar este pedido.</div><div className="mt-6 space-y-4"><div><label className="field-label">Seu nome</label><Input value={s.customer.name} onChange={(e) => s.setCustomer({ ...s.customer, name: e.target.value })} placeholder="Como podemos chamar você?" /></div><div><label className="field-label">WhatsApp</label><Input value={s.customer.phone} onChange={(e) => s.setCustomer({ ...s.customer, phone: e.target.value })} placeholder="(11) 99999-9999" />{s.historyQuery.data && s.historyQuery.data.length > 0 && <div className="mt-3 rounded-xl border border-[#e9e3d9] bg-white p-3"><p className="text-xs font-semibold uppercase tracking-wide text-[#a05c32]">Pedidos anteriores</p><div className="mt-2 space-y-2">{s.historyQuery.data.slice(0, 3).map(({ order }) => <div key={order.id} className="rounded-lg px-2 py-2 text-sm hover:bg-[#fbfaf7]"><button onClick={() => s.setSelectedHistoryId(order.id)} className="flex w-full items-center justify-between text-left"><span>Pedido #{order.id}</span><span className="text-[#a05c32]">R$ {Number(order.total).toFixed(2).replace(".", ",")}</span></button>{order.trackingUrl && <a href={order.trackingUrl} target="_blank" rel="noreferrer" className="mt-1 block text-xs font-semibold text-[#2f5d50] underline">Acompanhar entrega</a>}</div>)}</div></div>}</div><div><label className="field-label">Endereço de entrega</label><Textarea value={s.customer.address} onChange={(e) => s.setCustomer({ ...s.customer, address: e.target.value })} placeholder="Rua, número, complemento e bairro" /></div>
      {s.checkoutState.paymentEnabled && <div><label className="field-label">Email</label><Input type="email" value={s.customer.email} onChange={(e) => s.setCustomer({ ...s.customer, email: e.target.value })} placeholder="voce@exemplo.com" /></div>}
      {!s.checkoutState.paymentEnabled && <div><p className="field-label">Forma de pagamento</p><div className="grid grid-cols-3 gap-2">{([["pix", "PIX"], ["credit_card", "Crédito"], ["debit_card", "Débito"]] as const).map(([value, label]) => <button key={value} type="button" onClick={() => s.setPaymentMethod(value)} aria-pressed={s.paymentMethod === value} className={`rounded-xl border px-3 py-3 text-sm font-semibold transition ${s.paymentMethod === value ? "border-[#2f5d50] bg-[#e2f1e7] text-[#2f5d50]" : "border-[#e9e3d9] bg-white text-[#776e63]"}`}>{label}</button>)}</div></div>}
      <div className="rounded-2xl border border-[#e9e3d9] bg-white p-4"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#fff0d7] text-[#a05c32]"><Check className="h-4 w-4"/></div><div><p className="font-semibold">{s.checkoutState.title}</p><p className="text-xs text-[#776e63]">{s.checkoutState.notice}</p></div></div></div>

      {s.pixQrCode ? <div className="rounded-2xl border border-[#e9e3d9] bg-white p-4 text-center"><img src={`data:image/png;base64,${s.pixQrCode}`} alt="QR code Pix" className="mx-auto h-48 w-48" /><p className="mt-3 text-sm text-[#776e63]">Escaneie com o app do seu banco. Confirmamos automaticamente assim que o Pix cair.</p></div>
      : s.checkoutState.paymentEnabled && s.orderId && s.checkoutConfigQuery.data?.publicKey ? <MercadoPagoBrick publicKey={s.checkoutConfigQuery.data.publicKey} amount={s.total} payerEmail={s.customer.email} onSubmit={s.handleBrickSubmit} onError={(message) => toast.error(message)} />
      : s.checkoutState.paymentEnabled ? <Button onClick={s.ensureOrderCreated} disabled={s.createOrderMutation.isPending} className="h-12 w-full rounded-xl bg-[#2f5d50] text-white hover:bg-[#244b40]">{s.createOrderMutation.isPending ? "Preparando pagamento..." : "Ir para pagamento"} <ArrowRight className="ml-2 h-4 w-4"/></Button>
      : <><Button onClick={s.submitDemoOrder} disabled={s.createOrderMutation.isPending} className="h-12 w-full rounded-xl bg-[#2f5d50] text-white hover:bg-[#244b40]">{s.createOrderMutation.isPending ? "Registrando pedido..." : "Registrar pedido (modo demonstração)"} <ArrowRight className="ml-2 h-4 w-4"/></Button><p className="text-center text-xs text-[#a79b8d]">Seu pedido será registrado para a cozinha, mas nenhuma cobrança será criada enquanto o Mercado Pago estiver em modo demonstração.</p></>}
    </div></SheetContent></Sheet>
  </>;
}
